using System;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using Prescriva.Agent.Application.Configuration;
using Prescriva.Agent.Application.Inspection;
using Prescriva.Agent.Application.Runtime;
using Prescriva.Agent.Application.Testing;
using Prescriva.Agent.Desktop.Configuration;
using Prescriva.Agent.Desktop.Inspection;
using Prescriva.Agent.Desktop.Monitoring;
using Prescriva.Agent.Desktop.Overlay;
using Prescriva.Agent.Desktop.Shell;
using Prescriva.Agent.Desktop.Testing;
using Prescriva.Agent.Domain.Configuration;
using Prescriva.Agent.Infrastructure.Configuration;
using Prescriva.Agent.Infrastructure.Diagnostics;
using Prescriva.Agent.Infrastructure.Events;
using Prescriva.Agent.Infrastructure.Security;
using Prescriva.Agent.Windows.Automation;
using Prescriva.Agent.Windows.Processes;
using Prescriva.Agent.Windows.Runtime;
using Prescriva.Agent.Windows.Startup;

namespace Prescriva.Agent.Desktop;

/// <summary>
/// The configurator as a five-step guided assistant: 1 choose an open program from a list
/// (manual process/window entry stays as an advanced option), 2 mark fields and 3 buttons
/// with a live pointer-inspection session and a click-through highlight overlay - named in
/// plain words, their technical IDs generated by <see cref="SemanticIdGenerator"/> - then
/// 4 save and test, and 5 activate.
///
/// Deliberately thin - all real orchestration lives in <see cref="IntegrationEditorViewModel"/>
/// (Application-facing, testable with fakes) and <see cref="InspectorViewModel"/> (Task 4);
/// this class only wires them together and reacts to button clicks and a polling timer.
///
/// Also hosts the rest of the milestone flow: test mode (<see cref="TestModeViewModel"/>,
/// against the running target application), and activation/monitoring
/// (<see cref="RuntimeMonitorViewModel"/> over the real <see cref="AgentRuntime"/>, the
/// DPAPI-protected SQLite outbox and the JSON-lines technical log). Local data lives under
/// <see cref="DataDirectory"/>.
/// </summary>
public partial class MainWindow : Window
{
    private readonly AutomationDispatcher _automationDispatcher = new();
    private readonly InspectionController _inspectionController;
    private readonly InspectorViewModel _inspectorViewModel;
    private readonly IntegrationEditorViewModel _editorViewModel;
    private readonly HighlightOverlayWindow _overlay = new();
    private readonly DispatcherTimer _pointerPollTimer;

    private readonly UiAutomationRuntimeFactories _runtimeFactories;
    private readonly StructuredTechnicalLog _technicalLog;
    private readonly RuntimeMonitorViewModel _monitorViewModel;
    private readonly ApprovalService _approvalService;
    private readonly JsonConfigurationStore _configurationStore;
    private readonly JsonMonitoringPreferenceStore _monitoringPreference;
    private readonly IStartupRegistration _startupRegistration;
    private bool _updatingStartupOption;
    private readonly TrayIcon _trayIcon;
    private readonly SqliteEventOutbox _outbox;
    private readonly SqliteAttachmentStore _attachments;

    private readonly Win32OpenWindowSource _openWindowSource = new();
    private List<OpenWindowItem> _openWindows = [];
    private List<CaptureFieldChoice> _captureChoices = [];
    private IntegrationConfiguration? _listedConfiguration;
    private bool _settingGeneratedId;
    private bool _integrationIdEdited;
    private bool _fieldIdEdited;
    private bool _triggerIdEdited;

    private InspectionState? _confirmedSelection;
    private bool _exiting;
    private bool _hiddenNoticeShown;
    private TestModeViewModel? _testModeViewModel;

    public MainWindow()
    {
        InitializeComponent();

        var inspector = new UiAutomationElementInspector(_automationDispatcher);
        _inspectionController = new InspectionController(inspector, additionalExcludedProcessIds: [Environment.ProcessId]);
        _inspectorViewModel = new InspectorViewModel(_inspectionController, Dispatcher);
        _inspectorViewModel.PropertyChanged += (_, _) => OnInspectorStateChanged();

        var resolver = new UiAutomationSelectorResolver(_automationDispatcher);
        var captureProvider = new UiAutomationCaptureProvider(_automationDispatcher);
        var store = new JsonConfigurationStore(Path.Combine(DataDirectory, "configurations"));
        _configurationStore = store;
        _monitoringPreference = new JsonMonitoringPreferenceStore(DataDirectory);
        // Installed from the Store (MSIX) the Run key is virtualized: use the package's startup task.
        _startupRegistration = PackageIdentity.IsPackaged
            ? new PackagedStartupRegistration()
            : new RunKeyStartupRegistration(
                Environment.GetEnvironmentVariable("PRESCRIVA_AGENT_RUN_KEY") is { Length: > 0 } runKey ? runKey : RunKeyStartupRegistration.DefaultSubKey);
        _approvalService = new ApprovalService(new JsonApprovalStore(Path.Combine(DataDirectory, "approvals")));
        _editorViewModel = new IntegrationEditorViewModel(store, resolver, captureProvider);

        _runtimeFactories = new UiAutomationRuntimeFactories(_automationDispatcher);
        Directory.CreateDirectory(Path.Combine(DataDirectory, "logs"));
        _technicalLog = new StructuredTechnicalLog(Path.Combine(DataDirectory, "logs", "technical.jsonl"));
        var protector = new DpapiPayloadProtector();
        var outbox = new SqliteEventOutbox(Path.Combine(DataDirectory, "events.db"), protector);
        var attachments = new SqliteAttachmentStore(Path.Combine(DataDirectory, "events.db"), protector);
        _outbox = outbox;
        _attachments = attachments;
        var runtime = new AgentRuntime(
            new WindowsApplicationInstanceSource(),
            _runtimeFactories.CreateTriggerProvider,
            _runtimeFactories.CreateSelectorResolver,
            _runtimeFactories.CreateCaptureProvider,
            outbox,
            _technicalLog,
            attachments: attachments);
        _monitorViewModel = new RuntimeMonitorViewModel(
            runtime,
            outbox,
            Dispatcher,
            CreateCapacityPolicy(),
            async cancellationToken =>
            {
                await outbox.DeleteAllAsync(cancellationToken);
                await attachments.DeleteAllAsync(cancellationToken);
                _technicalLog.Clear();
            },
            attachments);
        _monitorViewModel.PropertyChanged += (_, _) => RefreshMonitor();
        Loaded += async (_, _) => await ApplyRetentionAsync(outbox, attachments);

        _trayIcon = new TrayIcon(ShowFromTray, () => StopMonitoringButton_Click(this, new RoutedEventArgs()), ExitApplication);
        StartWithWindowsCheckBox.Checked += async (_, _) => await SetStartWithWindowsAsync(true);
        StartWithWindowsCheckBox.Unchecked += async (_, _) => await SetStartWithWindowsAsync(false);
        Loaded += async (_, _) => await ShowStartupStateAsync();
        Loaded += async (_, _) =>
        {
            RefreshSavedIntegrations();
            RefreshWizardLists();
            UpdateStepButtons();
            await RefreshOpenWindowsAsync();
        };
        Closing += OnClosing;

        _pointerPollTimer = new DispatcherTimer(DispatcherPriority.Background)
        {
            Interval = TimeSpan.FromMilliseconds(80),
        };
        _pointerPollTimer.Tick += async (_, _) => await PollPointerAsync();

        Closed += async (_, _) =>
        {
            // Exiting keeps the integration "left active", so starting with Windows resumes it;
            // only the Stop button clears that choice.
            await _monitorViewModel.StopAsync();
            _trayIcon.Dispose();
            _technicalLog.Dispose();
            _pointerPollTimer.Stop();
            _overlay.Close();
            _inspectorViewModel.Dispose();
            _automationDispatcher.Dispose();
            System.Windows.Application.Current?.Shutdown();
        };
    }

    /// <summary>
    /// Started by "Iniciar com o Windows": the window stays hidden (the tray icon shows the
    /// Agent is running) and the integration the operator left active is resumed - only if
    /// its approval still matches its content. Any other outcome is shown, never activated.
    /// </summary>
    public async Task StartInBackgroundAsync()
    {
        await ApplyRetentionAsync(_outbox, _attachments);
        StartupDecision decision;
        try
        {
            decision = await new StartupActivation(_monitoringPreference, _configurationStore, _approvalService).DecideAsync(CancellationToken.None);
        }
        catch (Exception ex)
        {
            decision = new StartupDecision(StartupDecisionKind.ConfigurationUnavailable, ex.GetType().Name);
        }

        if (decision.Kind == StartupDecisionKind.Activate)
        {
            try
            {
                IntegrationIdBox.Text = decision.ConfigurationId;
                await _editorViewModel.ReloadAsync(decision.ConfigurationId!);
                await _monitorViewModel.StartAsync(decision.Configuration!, decision.Approval);
                SetStatus(decision.Describe());
                _trayIcon.Notify(TrayIcon.ProductName, decision.Describe());
            }
            catch (Exception ex)
            {
                // Never fail silently at sign-in: the tray stays, with the reason.
                var message = $"Iniciado com o Windows: não foi possível retomar '{decision.ConfigurationId}' ({ex.GetType().Name}); nada sendo monitorado.";
                SetStatus(message);
                _trayIcon.Notify(TrayIcon.ProductName, message, warning: true);
            }
        }
        else
        {
            SetStatus(decision.Describe());
            _trayIcon.Notify(TrayIcon.ProductName, decision.Describe(), warning: decision.Kind != StartupDecisionKind.NothingActive);
        }

        RefreshTrayStatus();
    }

    /// <summary>Shows the window (tray menu, double click, or a second start of the Agent).</summary>
    public void ShowFromTray()
    {
        Show();
        if (WindowState == WindowState.Minimized)
        {
            WindowState = WindowState.Normal;
        }

        Activate();
    }

    private void OnClosing(object? sender, CancelEventArgs e)
    {
        if (_exiting || !_monitorViewModel.IsMonitoring)
        {
            return;
        }

        // Closing the window must not silently stop monitoring: keep running in the tray.
        e.Cancel = true;
        Hide();
        if (!_hiddenNoticeShown)
        {
            _hiddenNoticeShown = true;
            _trayIcon.Notify(TrayIcon.ProductName, "Continua monitorando na bandeja. Use o ícone para abrir, parar ou sair.");
        }
    }

    private void ExitApplication()
    {
        _exiting = true;
        Close();
    }

    private async Task ShowStartupStateAsync()
    {
        try
        {
            ShowStartupState(await _startupRegistration.GetStateAsync(), announce: false);
        }
        catch (Exception ex)
        {
            SetStatus($"Estado de 'Iniciar com o Windows' indisponível ({ex.GetType().Name}).");
        }
    }

    private async Task SetStartWithWindowsAsync(bool enabled)
    {
        if (_updatingStartupOption)
        {
            return;
        }

        try
        {
            var state = enabled
                ? await _startupRegistration.EnableAsync(Environment.ProcessPath ?? throw new InvalidOperationException("Executable path unknown."))
                : await _startupRegistration.DisableAsync();
            ShowStartupState(state, announce: true);
        }
        catch (Exception ex)
        {
            SetStatus($"Não foi possível alterar 'Iniciar com o Windows': {ex.Message}");
        }
    }

    /// <summary>Shows the real state (which Windows may override) on the checkbox, with the reason when it differs.</summary>
    private void ShowStartupState(StartupRegistrationState state, bool announce)
    {
        var enabled = state is StartupRegistrationState.Enabled or StartupRegistrationState.EnabledByPolicy;
        _updatingStartupOption = true;
        try
        {
            StartWithWindowsCheckBox.IsChecked = enabled;
            StartWithWindowsCheckBox.IsEnabled = state is not (StartupRegistrationState.DisabledByPolicy or StartupRegistrationState.EnabledByPolicy);
        }
        finally
        {
            _updatingStartupOption = false;
        }

        var message = state switch
        {
            StartupRegistrationState.Enabled => "Iniciar com o Windows: ativado. O Agent abrirá na bandeja ao entrar no Windows e retomará a integração ativa, se aprovada.",
            StartupRegistrationState.DisabledByUser => "Iniciar com o Windows está desativado no Gerenciador de Tarefas (Aplicativos de inicialização). Ative o Receita Fácil Agent lá para que ele inicie com o Windows.",
            StartupRegistrationState.DisabledByPolicy => "Iniciar com o Windows foi bloqueado por uma política do administrador.",
            StartupRegistrationState.EnabledByPolicy => "Iniciar com o Windows foi ativado por uma política do administrador.",
            _ => "Iniciar com o Windows: desativado.",
        };

        if (announce || state is not (StartupRegistrationState.Enabled or StartupRegistrationState.Disabled))
        {
            SetStatus(message);
        }
    }

    private void RefreshTrayStatus() =>
        _trayIcon.SetStatus(_monitorViewModel.IsMonitoring
            ? $"{TrayIcon.ProductName} - monitorando '{_editorViewModel.Configuration?.Name}'"
            : $"{TrayIcon.ProductName} - parado");

    /// <summary>
    /// Where configurations, the event queue and technical logs are kept:
    /// %LOCALAPPDATA%\Prescriva\Agent, or the directory named by the
    /// PRESCRIVA_AGENT_DATA environment variable (used to isolate automated UI tests).
    /// </summary>
    internal static string DataDirectory =>
        Environment.GetEnvironmentVariable("PRESCRIVA_AGENT_DATA") is { Length: > 0 } overridden
            ? overridden
            : Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Prescriva", "Agent");

    private void CreateIntegrationButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(ProcessIdentityBox.Text))
            {
                SetStatus("Escolha um programa na lista e clique em 'Usar o programa selecionado' (ou digite o processo em 'Opções avançadas').");
                return;
            }

            if (string.IsNullOrWhiteSpace(IntegrationNameBox.Text) || string.IsNullOrWhiteSpace(IntegrationIdBox.Text))
            {
                SetStatus("Dê um nome à integração antes de criá-la.");
                return;
            }

            var application = new ApplicationDefinition(ProcessIdentityBox.Text.Trim(), WindowRuleBox.Text.Trim());
            _editorViewModel.CreateIntegration(IntegrationIdBox.Text.Trim(), IntegrationNameBox.Text.Trim(), application);
            SetStatus($"Integração '{_editorViewModel.Configuration!.Id}' criada. Agora marque os campos (passo 2). {UnsavedChanges()}");
        }
        catch (Exception ex)
        {
            SetStatus($"Não foi possível criar a integração: {ex.Message}");
        }
    }

    private void AddStageButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            _editorViewModel.AddStage(StageIdBox.Text.Trim(), StageNameBox.Text.Trim());
            SetStatus($"Etapa '{StageIdBox.Text.Trim()}' adicionada.");
        }
        catch (Exception ex)
        {
            SetStatus($"Não foi possível adicionar a etapa: {ex.Message}");
        }
    }

    private async void StartInspectionButton_Click(object sender, RoutedEventArgs e)
    {
        await _inspectorViewModel.StartAsync();
        _pointerPollTimer.Start();
        SetStatus("Seleção iniciada: passe o mouse sobre o campo ou botão na aplicação.");
    }

    private async void StopInspectionButton_Click(object sender, RoutedEventArgs e)
    {
        _pointerPollTimer.Stop();
        await _inspectorViewModel.StopAsync();
        _overlay.UpdateHighlight(null);
        SetStatus("Seleção parada.");
    }

    private async void ConfirmSelectionButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            var confirmed = await _inspectorViewModel.ConfirmAsync();
            _confirmedSelection = confirmed;
            var confirmedText =
                $"Confirmado: AutomationId='{confirmed.Snapshot?.AutomationId}', Nome='{confirmed.Snapshot?.Name}', Tipo='{confirmed.Snapshot?.ControlType}', Rótulo='{LabelOf(confirmed.Snapshot)}'.";
            ConfirmedSelectionText.Text = confirmedText;
            TriggerConfirmedSelectionText.Text = confirmedText;
            SetStatus(WizardSteps.SelectedItem == Step3Tab
                ? "Elemento escolhido. Dê um nome ao botão, marque os campos que ele lê e clique em 'Adicionar botão'."
                : "Elemento escolhido. Dê um nome ao campo e clique em 'Adicionar campo'.");
        }
        catch (InvalidOperationException ex)
        {
            SetStatus($"Não foi possível confirmar: {ex.Message}");
        }
    }

    private void AddFieldButton_Click(object sender, RoutedEventArgs e)
    {
        if (_editorViewModel.Configuration is null)
        {
            SetStatus("Crie ou abra uma integração no passo 1 antes de marcar campos.");
            return;
        }

        if (_confirmedSelection?.Fingerprint is not { } fingerprint)
        {
            SetStatus("Primeiro marque o campo no programa: 'Começar a marcar', passe o mouse sobre ele e clique em 'Usar este elemento'.");
            return;
        }

        if (string.IsNullOrWhiteSpace(FieldSemanticIdBox.Text))
        {
            SetStatus("Dê um nome ao campo (ex.: Medicamento) antes de adicioná-lo.");
            return;
        }

        try
        {
            var stageId = EnsureStage();
            var fieldId = FieldSemanticIdBox.Text.Trim();
            _editorViewModel.AddField(
                fieldId,
                stageId,
                FieldMeaningBox.Text.Trim(),
                FieldRequiredBox.IsChecked == true,
                fingerprint,
                FieldKindBox.SelectedIndex switch
                {
                    1 => FieldKind.File,
                    2 => FieldKind.OcrText,
                    _ => FieldKind.Text,
                });
            ResetFieldForm();
            SetStatus($"Campo '{fieldId}' adicionado. {UnsavedChanges()}");
        }
        catch (ArgumentException ex)
        {
            SetStatus($"ID inválido: {ex.Message}");
        }
        catch (InvalidOperationException ex)
        {
            SetStatus($"Não foi possível adicionar o campo: {ex.Message}");
        }
    }

    private void AddTriggerButton_Click(object sender, RoutedEventArgs e)
    {
        if (_editorViewModel.Configuration is null)
        {
            SetStatus("Crie ou abra uma integração no passo 1 antes de marcar botões.");
            return;
        }

        if (_confirmedSelection?.Fingerprint is not { } fingerprint)
        {
            SetStatus("Primeiro marque o botão no programa: 'Começar a marcar', passe o mouse sobre ele e clique em 'Usar este elemento'.");
            return;
        }

        if (string.IsNullOrWhiteSpace(TriggerSemanticIdBox.Text))
        {
            SetStatus("Dê um nome ao botão (ex.: Adicionar item) antes de adicioná-lo.");
            return;
        }

        try
        {
            var stageId = EnsureStage();
            var triggerId = TriggerSemanticIdBox.Text.Trim();
            var actions = TriggerActionsBuilder.Build(
                CheckedCaptureFields(),
                TriggerEmitEventBox.Text,
                TriggerTransitionStageBox.Text,
                TriggerClearStateBox.IsChecked == true,
                (TriggerTerminalAction)Math.Max(0, TriggerTerminalBox.SelectedIndex));
            _editorViewModel.AddTrigger(
                triggerId,
                stageId,
                fingerprint,
                TriggerObservedEventBox.Text.Trim(),
                actions);
            ResetTriggerForm();
            SetStatus($"Gatilho '{triggerId}' adicionado com {actions.Length} ação(ões). {UnsavedChanges()}");
        }
        catch (ArgumentException ex)
        {
            SetStatus($"Gatilho inválido: {ex.Message}");
        }
        catch (InvalidOperationException ex)
        {
            SetStatus($"Não foi possível adicionar o gatilho: {ex.Message}");
        }
    }

    private void RemoveStageButton_Click(object sender, RoutedEventArgs e) =>
        Edit(() => _editorViewModel.RemoveStage(StageIdBox.Text.Trim()), $"Etapa '{StageIdBox.Text.Trim()}' removida.");

    private void UpdateFieldButton_Click(object sender, RoutedEventArgs e) =>
        Edit(
            () => _editorViewModel.UpdateField(FieldSemanticIdBox.Text.Trim(), FieldMeaningBox.Text.Trim(), FieldRequiredBox.IsChecked == true),
            $"Campo '{FieldSemanticIdBox.Text.Trim()}' atualizado.");

    private void RemoveFieldButton_Click(object sender, RoutedEventArgs e) =>
        Edit(() => _editorViewModel.RemoveField(FieldSemanticIdBox.Text.Trim()), $"Campo '{FieldSemanticIdBox.Text.Trim()}' removido.");

    private void ReplaceTriggerActionsButton_Click(object sender, RoutedEventArgs e) =>
        Edit(
            () => _editorViewModel.ReplaceTriggerActions(
                TriggerSemanticIdBox.Text.Trim(),
                TriggerActionsBuilder.Build(
                    CheckedCaptureFields(),
                    TriggerEmitEventBox.Text,
                    TriggerTransitionStageBox.Text,
                    TriggerClearStateBox.IsChecked == true,
                    (TriggerTerminalAction)Math.Max(0, TriggerTerminalBox.SelectedIndex))),
            $"Ações do gatilho '{TriggerSemanticIdBox.Text.Trim()}' substituídas.");

    private void RemoveTriggerButton_Click(object sender, RoutedEventArgs e) =>
        Edit(() => _editorViewModel.RemoveTrigger(TriggerSemanticIdBox.Text.Trim()), $"Gatilho '{TriggerSemanticIdBox.Text.Trim()}' removido.");

    /// <summary>Applies one editor operation, reporting a refusal instead of applying part of it.</summary>
    private void Edit(Action edit, string success)
    {
        try
        {
            edit();
            SetStatus($"{success} {UnsavedChanges()}");
        }
        catch (Exception ex) when (ex is InvalidOperationException or ArgumentException)
        {
            SetStatus($"Edição recusada: {ex.Message}");
        }
    }

    /// <summary>Shows whether the current configuration content may be activated.</summary>
    private async Task RefreshApprovalStateAsync()
    {
        if (_editorViewModel.Configuration is not { } configuration)
        {
            ApprovalStateText.Text = "(nenhuma integração)";
            return;
        }

        try
        {
            var status = await _approvalService.GetStatusAsync(configuration);
            ApprovalStateText.Text = status.State switch
            {
                ApprovalState.Approved => $"Aprovada em {status.LastApprovedAtUtc!.Value.ToLocalTime():g}: pode ser ativada.",
                ApprovalState.ChangedSinceTest => $"Alterada desde o último teste aprovado ({status.LastApprovedAtUtc!.Value.ToLocalTime():g}): teste e aprove novamente para ativar.",
                _ => "Não testada: execute o modo de teste e aprove antes de ativar.",
            };
            ApprovalStateText.Foreground = status.State == ApprovalState.Approved
                ? System.Windows.Media.Brushes.DarkGreen
                : System.Windows.Media.Brushes.DarkOrange;
        }
        catch (Exception ex) when (ex is ArgumentException or IOException)
        {
            ApprovalStateText.Text = $"Estado de aprovação indisponível ({ex.GetType().Name}).";
        }
    }

    private async void SaveButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            await _editorViewModel.SaveAsync();
            RefreshSavedIntegrations();
            SetStatus($"Salvo. {UnsavedChanges()}");
        }
        catch (ConfigurationValidationException ex)
        {
            SetStatus($"Não foi salvo: a configuração é inválida ({string.Join("; ", ex.Errors.Select(err => err.Code))}).");
        }
        catch (Exception ex)
        {
            SetStatus($"Falha ao salvar: {ex.Message}");
        }
    }

    private async void ReloadButton_Click(object sender, RoutedEventArgs e)
    {
        if (string.IsNullOrWhiteSpace(IntegrationIdBox.Text))
        {
            SetStatus("Escolha uma integração salva na lista para abri-la.");
            return;
        }

        try
        {
            await _editorViewModel.ReloadAsync(IntegrationIdBox.Text.Trim());
            SetStatus($"Integração '{_editorViewModel.Configuration!.Id}' recarregada com {_editorViewModel.Configuration.Fields.Length} campo(s).");
        }
        catch (Exception ex)
        {
            SetStatus($"Falha ao recarregar: {ex.Message}");
        }
    }

    private async void ResolveButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            if (ResolveFieldBox.SelectedValue is not string fieldId)
            {
                SetStatus("Escolha um campo na lista para localizá-lo.");
                return;
            }

            var resolution = await _editorViewModel.ResolveFieldAsync(fieldId);
            SetStatus($"Localização: {resolution.Status} (confiança {resolution.Confidence:P0}).");
        }
        catch (Exception ex)
        {
            SetStatus($"Falha ao localizar: {ex.Message}");
        }
    }

    private async void ReadValueButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            if (ResolveFieldBox.SelectedValue is not string fieldId)
            {
                SetStatus("Escolha um campo na lista para ler o valor.");
                return;
            }

            var result = await _editorViewModel.ReadFieldValueAsync(fieldId);
            SetStatus($"Leitura: resultado={result.Outcome}, valor='{result.Value}'.");
        }
        catch (Exception ex)
        {
            SetStatus($"Falha na leitura: {ex.Message}");
        }
    }

    private async void PrepareTestButton_Click(object sender, RoutedEventArgs e)
    {
        if (_editorViewModel.Configuration is not { } configuration)
        {
            SetStatus("Crie ou recarregue uma integração antes de testá-la.");
            return;
        }

        var running = await FindRunningProcessIdsAsync(configuration.Application);
        if (running.Count == 0)
        {
            SetStatus($"Aplicação '{configuration.Application.ProcessIdentity}' com janela '{configuration.Application.WindowRule}' não está em execução. Abra-a e tente novamente.");
            return;
        }

        if (running.Count > 1)
        {
            // Never pick one of several identical windows silently.
            SetStatus($"Há {running.Count} janelas '{configuration.Application.WindowRule}' de '{configuration.Application.ProcessIdentity}' abertas. Deixe só uma aberta para testar.");
            return;
        }

        int? processId = running[0];

        var instance = new ApplicationInstance(Guid.NewGuid(), processId.Value);
        var runner = new IntegrationTestRunner(
            _runtimeFactories.CreateSelectorResolver(instance),
            _runtimeFactories.CreateCaptureProvider(instance),
            _runtimeFactories.CreateTriggerProvider(instance, Guid.NewGuid()),
            triggerTimeout: TimeSpan.FromSeconds(15));
        _testModeViewModel = new TestModeViewModel(runner, Dispatcher, approvals: _approvalService);
        TestModeHost.Attach(_testModeViewModel, configuration);
        TestModeHost.Approved -= OnTestApproved;
        TestModeHost.Approved += OnTestApproved;
        TestModeHost.Visibility = Visibility.Visible;
        SetStatus($"Teste preparado para o processo {processId}. Clique em 'Executar teste' e, na aplicação, pressione cada botão configurado, na ordem, em até 15 segundos cada.");
    }

    private async void ActivateButton_Click(object sender, RoutedEventArgs e)
    {
        if (_editorViewModel.Configuration is not { } configuration)
        {
            SetStatus("Crie ou recarregue uma integração antes de ativá-la.");
            return;
        }

        try
        {
            // The stored approval for exactly this content, if any; AgentRuntime enforces the gate.
            var approval = (await _approvalService.GetStatusAsync(configuration)).Approval;
            var status = await _monitorViewModel.StartAsync(configuration, approval);
            if (status == ActivationStatus.Activated)
            {
                await _monitoringPreference.SetActiveConfigurationIdAsync(configuration.Id, CancellationToken.None);
            }
            else if (_testModeViewModel is not null)
            {
                _testModeViewModel.GateMessage = _monitorViewModel.StatusText;
            }
        }
        catch (InvalidOperationException ex)
        {
            SetStatus(ex.Message);
        }
    }

    private async void OnTestApproved(object? sender, EventArgs e) => await RefreshApprovalStateAsync();

    private async void StopMonitoringButton_Click(object sender, RoutedEventArgs e)
    {
        await _monitorViewModel.StopAsync();
        await _monitoringPreference.SetActiveConfigurationIdAsync(null, CancellationToken.None);
    }

    private async void ClearLocalDataButton_Click(object sender, RoutedEventArgs e)
    {
        var answer = MessageBox.Show(
            this,
            "Apagar TODOS os eventos da fila local (inclusive os ainda não confirmados) e o log técnico? Esta ação não pode ser desfeita. As configurações são mantidas.",
            "Limpar dados locais",
            MessageBoxButton.YesNo,
            MessageBoxImage.Warning,
            MessageBoxResult.No);
        if (answer != MessageBoxResult.Yes)
        {
            return;
        }

        try
        {
            await _monitorViewModel.ClearLocalDataAsync();
        }
        catch (Exception ex)
        {
            SetStatus($"Falha ao limpar os dados locais: {ex.GetType().Name}.");
        }
    }

    /// <summary>
    /// Pending-event alert thresholds: 1000 (warning) and 5000 (critical) by default, or the
    /// PRESCRIVA_AGENT_OUTBOX_WARNING / PRESCRIVA_AGENT_OUTBOX_CRITICAL environment variables.
    /// </summary>
    private static OutboxCapacityPolicy CreateCapacityPolicy()
    {
        static int Read(string name, int fallback) =>
            int.TryParse(Environment.GetEnvironmentVariable(name), out var value) && value >= 0 ? value : fallback;

        var warning = Read("PRESCRIVA_AGENT_OUTBOX_WARNING", 1000);
        var critical = Math.Max(warning, Read("PRESCRIVA_AGENT_OUTBOX_CRITICAL", 5000));
        return new OutboxCapacityPolicy(warning, critical);
    }

    private void RefreshMonitor()
    {
        MonitorStatusText.Text = _monitorViewModel.StatusText;
        var diagnostics = _monitorViewModel.Diagnostics;
        DiagnosticsList.ItemsSource = diagnostics;
        EventsList.ItemsSource = _monitorViewModel.Events;
        if (diagnostics.Count > 0)
        {
            DiagnosticsList.ScrollIntoView(diagnostics[^1]);
        }

        ActivateButton.IsEnabled = !_monitorViewModel.IsMonitoring;
        RefreshTrayStatus();
        StopMonitoringButton.IsEnabled = _monitorViewModel.IsMonitoring;
        ClearLocalDataButton.IsEnabled = !_monitorViewModel.IsMonitoring;

        HealthText.Text = _monitorViewModel.HealthText;
        HealthText.Foreground = _monitorViewModel.HealthState switch
        {
            IntegrationHealthState.Broken => System.Windows.Media.Brushes.DarkRed,
            IntegrationHealthState.Degraded => System.Windows.Media.Brushes.DarkOrange,
            _ => System.Windows.Media.Brushes.DarkGreen,
        };

        var alert = _monitorViewModel.CapacityAlert;
        CapacityAlertText.Text = alert ?? string.Empty;
        CapacityAlertText.Foreground = _monitorViewModel.IsCapacityCritical ? System.Windows.Media.Brushes.DarkRed : System.Windows.Media.Brushes.DarkOrange;
        CapacityAlertText.Visibility = alert is null ? Visibility.Collapsed : Visibility.Visible;
    }

    private async Task ApplyRetentionAsync(SqliteEventOutbox outbox, SqliteAttachmentStore attachments)
    {
        try
        {
            await new RetentionService(outbox).ApplyAsync(System.Threading.CancellationToken.None);
            await LocalDataMaintenance.CollectAttachmentGarbageAsync(outbox, attachments, System.Threading.CancellationToken.None);
            await _monitorViewModel.RefreshEventsAsync();
        }
        catch (Exception ex)
        {
            SetStatus($"Fila local de eventos indisponível: {ex.GetType().Name}.");
        }
    }

    /// <summary>
    /// The processes showing the configured program's window, found through the open-window
    /// list - so a Store app framed by ApplicationFrameHost is found by its content process.
    /// </summary>
    private async Task<IReadOnlyList<int>> FindRunningProcessIdsAsync(ApplicationDefinition application)
    {
        var windows = await _openWindowSource.ListAsync(CancellationToken.None);
        return windows
            .Where(window => ProcessIdentity.Matches(application.ProcessIdentity, window.ProcessName) &&
                (string.IsNullOrWhiteSpace(application.WindowRule) ||
                 string.Equals(window.WindowTitle, application.WindowRule, StringComparison.OrdinalIgnoreCase)))
            .Select(window => window.ProcessId)
            .Distinct()
            .ToList();
    }

    private string UnsavedChanges() =>
        _editorViewModel.HasUnsavedChanges ? "Alterações não salvas: sim." : "Alterações não salvas: não.";

    private void RefreshConfigurationSummary()
    {
        if (_editorViewModel.Configuration is not { } configuration)
        {
            ConfigurationSummaryText.Text = "(nenhuma integração)";
            return;
        }

        var stages = string.Join(", ", configuration.Stages.Select(stage => stage.Id));
        var fields = string.Join(", ", configuration.Fields.Select(field => $"{field.Id}@{field.StageId}{(field.Required ? "*" : "")}{field.Kind switch { FieldKind.File => "[file]", FieldKind.OcrText => "[ocr]", _ => "" }}"));
        var triggers = string.Join(" | ", configuration.Triggers.Select(trigger =>
            $"{trigger.Id}@{trigger.StageId}: {string.Join(" > ", trigger.Actions.Select(DescribeAction))}"));
        ConfigurationSummaryText.Text =
            $"'{configuration.Id}' → {configuration.Application.ProcessIdentity}\nEtapas: {stages}\nCampos: {fields}\nGatilhos: {triggers}";
    }

    private static string DescribeAction(TriggerActionDefinition action) => action switch
    {
        CaptureFieldsAction capture => $"capture({string.Join(",", capture.FieldIds)})",
        EmitEventAction emit => $"emit({emit.EventType})",
        TransitionStageAction transition => $"goto({transition.StageId})",
        ClearStateAction => "clear",
        FinishSessionAction => "finish",
        CancelSessionAction => "cancel",
        _ => action.GetType().Name,
    };

    private async System.Threading.Tasks.Task PollPointerAsync()
    {
        if (!GetCursorPos(out var point))
        {
            return;
        }

        await _inspectorViewModel.ObservePointerAsync(new ScreenPoint(point.X, point.Y));
    }

    private void OnInspectorStateChanged()
    {
        _overlay.UpdateHighlight(_inspectorViewModel.Bounds);

        var snapshot = _inspectorViewModel.Snapshot;
        var hover = snapshot is not null
            ? $"Sob o cursor: AutomationId='{snapshot.AutomationId}', Nome='{snapshot.Name}', Tipo='{snapshot.ControlType}', Rótulo='{LabelOf(snapshot)}'."
            : _inspectorViewModel.Warnings.Length > 0
                ? string.Join(" ", _inspectorViewModel.Warnings)
                : "(nada sob o cursor)";
        HoverStateText.Text = hover;
        TriggerHoverStateText.Text = hover;
    }

    private static string LabelOf(ElementSnapshot? snapshot) =>
        snapshot is null || snapshot.NearbyLabels.IsDefaultOrEmpty ? string.Empty : snapshot.NearbyLabels[0];

    private void SetStatus(string message)
    {
        StatusText.Text = message;
        RefreshConfigurationSummary();
        RefreshWizardLists();
        _ = RefreshApprovalStateAsync();
    }

    // ---- Step 1: choose the program -------------------------------------------------

    /// <summary>
    /// Lists the open programs (name, title, process, PID - kept in memory only, never logged
    /// or saved) with their icons.
    /// </summary>
    private async Task RefreshOpenWindowsAsync()
    {
        RefreshWindowsButton.IsEnabled = false;
        try
        {
            var windows = await _openWindowSource.ListAsync(CancellationToken.None);
            _openWindows = await Task.Run(() => windows.Select(OpenWindowItem.Create).ToList());
            ApplyWindowFilter();
        }
        catch (Exception ex)
        {
            SetStatus($"Não foi possível listar os programas abertos ({ex.GetType().Name}). Use 'Opções avançadas' para digitar o processo e a janela.");
        }
        finally
        {
            RefreshWindowsButton.IsEnabled = true;
        }
    }

    private void ApplyWindowFilter()
    {
        var query = OpenWindowsSearchBox.Text;
        var visible = OpenWindowFilter.Apply(_openWindows.Select(item => item.Info), query)
            .Select(info => _openWindows.First(item => item.Info == info))
            .ToList();
        OpenWindowsList.ItemsSource = visible;
        OpenWindowsEmptyText.Text = _openWindows.Count == 0
            ? "Nenhum programa aberto encontrado. Abra o programa que você quer integrar e clique em 'Atualizar lista'."
            : $"Nenhum programa corresponde a '{query.Trim()}'. Apague a busca ou tente outra palavra.";
        OpenWindowsEmptyText.Visibility = visible.Count == 0 ? Visibility.Visible : Visibility.Collapsed;
        UseSelectedWindowButton.IsEnabled = OpenWindowsList.SelectedItem is not null;
    }

    private async void RefreshWindowsButton_Click(object sender, RoutedEventArgs e) => await RefreshOpenWindowsAsync();

    private void OpenWindowsSearchBox_TextChanged(object sender, TextChangedEventArgs e) => ApplyWindowFilter();

    private void OpenWindowsList_SelectionChanged(object sender, SelectionChangedEventArgs e) =>
        UseSelectedWindowButton.IsEnabled = OpenWindowsList.SelectedItem is not null;

    private void OpenWindowsList_MouseDoubleClick(object sender, System.Windows.Input.MouseButtonEventArgs e) => UseSelectedWindow();

    private void UseSelectedWindowButton_Click(object sender, RoutedEventArgs e) => UseSelectedWindow();

    /// <summary>Fills the process and window title from the chosen program (and the name, if still empty).</summary>
    private void UseSelectedWindow()
    {
        if (OpenWindowsList.SelectedItem is not OpenWindowItem { Info: var window })
        {
            SetStatus("Escolha um programa na lista primeiro.");
            return;
        }

        ProcessIdentityBox.Text = window.ProcessName + ".exe";
        WindowRuleBox.Text = window.WindowTitle;
        if (string.IsNullOrWhiteSpace(IntegrationNameBox.Text))
        {
            IntegrationNameBox.Text = window.AppName;
        }

        ChosenProgramText.Text = $"Programa escolhido: {window.AppName} — janela '{window.WindowTitle}' (processo {window.ProcessName}.exe).";
        SetStatus("Programa escolhido. Confira o nome da integração e clique em 'Criar integração'.");
    }

    private void IntegrationNameBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (!_integrationIdEdited && IntegrationIdBox is not null)
        {
            var saved = _configurationStore?.ListIds() ?? [];
            SetGenerated(IntegrationIdBox, string.IsNullOrWhiteSpace(IntegrationNameBox.Text)
                ? string.Empty
                : SemanticIdGenerator.FromName(IntegrationNameBox.Text, saved, "integracao"));
        }
    }

    private void IntegrationIdBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (!_settingGeneratedId)
        {
            _integrationIdEdited = IntegrationIdBox.Text.Length > 0;
        }
    }

    private void RefreshSavedIntegrations()
    {
        IReadOnlyList<string> ids;
        try
        {
            ids = _configurationStore.ListIds();
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            ids = [];
        }

        SavedIntegrationsList.ItemsSource = ids;
        SavedIntegrationsEmptyText.Visibility = ids.Count == 0 ? Visibility.Visible : Visibility.Collapsed;
    }

    private void SavedIntegrationsList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (SavedIntegrationsList.SelectedItem is string id)
        {
            IntegrationIdBox.Text = id;
        }
    }

    // ---- Steps 2 and 3: fields and buttons -------------------------------------------

    /// <summary>The stage new fields and buttons go to; a simple integration's only stage is created on first use.</summary>
    private string EnsureStage()
    {
        var stageId = StageIdBox.Text.Trim();
        if (_editorViewModel.Configuration is { Stages.Length: 0 })
        {
            _editorViewModel.AddStage(stageId, StageNameBox.Text.Trim());
        }

        return stageId;
    }

    private void FieldMeaningBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (!_fieldIdEdited && FieldSemanticIdBox is not null)
        {
            var existing = _editorViewModel?.Configuration?.Fields.Select(field => field.Id) ?? [];
            SetGenerated(FieldSemanticIdBox, string.IsNullOrWhiteSpace(FieldMeaningBox.Text)
                ? string.Empty
                : SemanticIdGenerator.FromName(FieldMeaningBox.Text, existing, "campo"));
        }
    }

    private void FieldSemanticIdBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (!_settingGeneratedId)
        {
            _fieldIdEdited = FieldSemanticIdBox.Text.Length > 0;
        }
    }

    private void TriggerNameBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (!_triggerIdEdited && TriggerSemanticIdBox is not null)
        {
            var existing = _editorViewModel?.Configuration?.Triggers.Select(trigger => trigger.Id) ?? [];
            SetGenerated(TriggerSemanticIdBox, string.IsNullOrWhiteSpace(TriggerNameBox.Text)
                ? string.Empty
                : SemanticIdGenerator.FromName(TriggerNameBox.Text, existing, "botao"));
        }
    }

    private void TriggerSemanticIdBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (!_settingGeneratedId)
        {
            _triggerIdEdited = TriggerSemanticIdBox.Text.Length > 0;
        }
    }

    /// <summary>Sets an ID box from its friendly name without marking it as typed by the user.</summary>
    private void SetGenerated(TextBox box, string value)
    {
        _settingGeneratedId = true;
        try
        {
            box.Text = value;
        }
        finally
        {
            _settingGeneratedId = false;
        }
    }

    private void ResetFieldForm()
    {
        SetGenerated(FieldSemanticIdBox, string.Empty);
        _fieldIdEdited = false;
        FieldMeaningBox.Text = string.Empty;
        FieldRequiredBox.IsChecked = true;
        FieldKindBox.SelectedIndex = 0;
    }

    private void ResetTriggerForm()
    {
        SetGenerated(TriggerSemanticIdBox, string.Empty);
        _triggerIdEdited = false;
        TriggerNameBox.Text = string.Empty;
        foreach (var choice in _captureChoices)
        {
            choice.IsChecked = false;
        }

        _listedConfiguration = null; // redraw the checkboxes unchecked
    }

    /// <summary>The checked "read these fields" boxes, in the order the fields were added.</summary>
    private string CheckedCaptureFields() =>
        string.Join(",", _captureChoices.Where(choice => choice.IsChecked).Select(choice => choice.Id));

    private void FieldsList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (FieldsList.SelectedItem is not FieldItem { Field: var field })
        {
            return;
        }

        FieldSemanticIdBox.Text = field.Id; // an existing ID: typed, not generated
        FieldMeaningBox.Text = field.Meaning;
        FieldRequiredBox.IsChecked = field.Required;
        FieldKindBox.SelectedIndex = field.Kind switch
        {
            FieldKind.File => 1,
            FieldKind.OcrText => 2,
            _ => 0,
        };
    }

    private void TriggersList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (TriggersList.SelectedItem is not TriggerItem { Trigger: var trigger })
        {
            return;
        }

        TriggerSemanticIdBox.Text = trigger.Id;
        TriggerObservedEventBox.Text = trigger.ObservedEvent;
        var captured = trigger.Actions.OfType<CaptureFieldsAction>().SelectMany(action => action.FieldIds).ToHashSet(StringComparer.Ordinal);
        foreach (var choice in _captureChoices)
        {
            choice.IsChecked = captured.Contains(choice.Id);
        }

        CaptureFieldsList.ItemsSource = null;
        CaptureFieldsList.ItemsSource = _captureChoices;
        TriggerEmitEventBox.Text = trigger.Actions.OfType<EmitEventAction>().FirstOrDefault()?.EventType ?? string.Empty;
        TriggerTransitionStageBox.Text = trigger.Actions.OfType<TransitionStageAction>().FirstOrDefault()?.StageId ?? string.Empty;
        TriggerClearStateBox.IsChecked = trigger.Actions.OfType<ClearStateAction>().Any();
        TriggerTerminalBox.SelectedIndex = trigger.Actions.OfType<FinishSessionAction>().Any() ? 1
            : trigger.Actions.OfType<CancelSessionAction>().Any() ? 2
            : 0;
    }

    /// <summary>Redraws the field, button and checkbox lists when the configuration changed.</summary>
    private void RefreshWizardLists()
    {
        var configuration = _editorViewModel?.Configuration;
        if (ReferenceEquals(configuration, _listedConfiguration) && configuration is not null)
        {
            return;
        }

        _listedConfiguration = configuration;
        var fields = configuration?.Fields ?? [];
        var triggers = configuration?.Triggers ?? [];

        FieldsList.ItemsSource = fields.Select(field => new FieldItem(field)).ToList();
        FieldsEmptyText.Visibility = fields.Length == 0 ? Visibility.Visible : Visibility.Collapsed;

        var names = fields.ToDictionary(field => field.Id, field => field.Meaning, StringComparer.Ordinal);
        TriggersList.ItemsSource = triggers.Select(trigger => new TriggerItem(trigger, names)).ToList();
        TriggersEmptyText.Visibility = triggers.Length == 0 ? Visibility.Visible : Visibility.Collapsed;

        var wasChecked = _captureChoices.Where(choice => choice.IsChecked).Select(choice => choice.Id).ToHashSet(StringComparer.Ordinal);
        _captureChoices = fields.Select(field => new CaptureFieldChoice(field.Id, field.Meaning, wasChecked.Contains(field.Id))).ToList();
        CaptureFieldsList.ItemsSource = _captureChoices;
        CaptureFieldsEmptyText.Visibility = fields.Length == 0 ? Visibility.Visible : Visibility.Collapsed;

        var selectedField = ResolveFieldBox.SelectedValue as string;
        ResolveFieldBox.SelectedValuePath = "Field.Id";
        ResolveFieldBox.ItemsSource = fields.Select(field => new FieldItem(field)).ToList();
        ResolveFieldBox.SelectedValue = selectedField is not null && names.ContainsKey(selectedField)
            ? selectedField
            : fields.FirstOrDefault()?.Id;

        CurrentIntegrationText.Text = configuration is null
            ? "Nenhuma integração aberta. Comece pelo passo 1."
            : $"Integração '{configuration.Name}' · programa {configuration.Application.ProcessIdentity} · {fields.Length} campo(s), {triggers.Length} botão(ões)";
    }

    // ---- Step navigation --------------------------------------------------------------

    private void BackStepButton_Click(object sender, RoutedEventArgs e) =>
        WizardSteps.SelectedIndex = Math.Max(0, WizardSteps.SelectedIndex - 1);

    private void NextStepButton_Click(object sender, RoutedEventArgs e) =>
        WizardSteps.SelectedIndex = Math.Min(WizardSteps.Items.Count - 1, WizardSteps.SelectedIndex + 1);

    private void WizardSteps_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        // Lists and combo boxes inside the steps raise the same (bubbling) event.
        if (ReferenceEquals(e.OriginalSource, WizardSteps))
        {
            UpdateStepButtons();
        }
    }

    private void UpdateStepButtons()
    {
        if (BackStepButton is null || NextStepButton is null)
        {
            return;
        }

        BackStepButton.IsEnabled = WizardSteps.SelectedIndex > 0;
        NextStepButton.IsEnabled = WizardSteps.SelectedIndex < WizardSteps.Items.Count - 1;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct PointStruct
    {
        public int X;
        public int Y;
    }

    [DllImport("user32.dll")]
    private static extern bool GetCursorPos(out PointStruct point);
}
